version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongo'
  timesheet_app:
    image: 'timesheet_app'
    container_name: 'timesheet_app'
    ports:
      - '8080:8080'
      - '8086:8086'
    depends_on:
      - 'mongo'