object Dependencies {
  val ProjectScalaVersion     = "2.13.1"
  val Http4sVersion           = "0.21.0-M5"
  val CirceVersion            = "0.12.3"
  val Specs2Version           = "4.8.0"
  val ScalaTestVersion        = "3.1.0"
  val LogbackVersion          = "1.2.3"
  val MonixVersion            = "3.0.0"
  val tsecV                   = "0.2.0-M1"
  val AVSystemCommonsVersion  = "2.0.0-M4"
  val MongoScalaDriver        = "2.7.0"
  val FS2Version              = "2.0.0"
  val silencerVersion         = "1.4.4"
  val PureConfigVersion       = "0.12.1"
  val CatsVersion             = "2.0.0"
  val KindProjectorVersion    = "0.10.3"
  val BetterMonadicForVersion = "0.3.1"
}
